# Site settings
title: CS378 Summer 2015&#58; Ivan Valle
email: ivanmartinvalle@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The home of my blog for CS 378: Generic Programming and the STL
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ivanmartinvalle.github.io" # the base hostname & protocol for your site
twitter_username: ivanmartinvalle
github_username:  ivanmartinvalle

# Build settings
markdown: kramdown
